name: Build & Test

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: complaints_boyaca
          MYSQL_USER: complaints_user
          MYSQL_PASSWORD: secure_password_2024
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (Backend)
        run: npm install

      - name: Run build check (Backend)
        run: npm run build --if-present

      - name: Install dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Run build (Frontend)
        working-directory: ./frontend
        run: npm run build
